### ISSUE TITLE
Interested in helping pick this up 

### ISSUE THREAD

**Issue by carbonatedcaffeine** [NeoAshers/pmaports-galileo#1]
Hi, the contact details on your postmarketOS page didn't work, so here I am! I was interested in helping work on this.

**Comment by UsrBinLuna** [comment]
sorry for responding so late, haven't been checking my email/notifs

you are more than welcome to work on this port, but just so you know, you are most probably going to end with a bricked gwatch due to pmOS modifying some critical partitions. it will boot into WIRED download mode, and so far i don't know how to continue from there, as i don't have the right screwdriver to open the watch and see what one can do to get it out
